name: 'runner-stats-action'
description:
  'Report resource statistics for the active runner, before and after a workflow
  run.'
author: 'Kris Cottingham <krisalyssa@cottingham.net>'

branding:
  icon: 'pie-chart' # bar-chart-2, cpu, database, hard-drive, pie-chart
  color: 'blue'

runs:
  using: node20
  main: dist/index.js
  post: dist/post.js
